### PR TITLE
Aligned all kernel patches to get the BPI-M2U to the updated 3.10.106 release

### PR DESCRIPTION
**Pull request by dan-and**
Hi,

Since my patches work pretty well on my side, it would be great if you update your base to the current 3.10.106 linux kernel release.

Kind regards,

Daniel

### CODE REVIEW

**Comment by ThomasKaiser** [comment]
Unbelievable: http://www.cnx-software.com/2017/05/29/banana-pi-bpi-m2-berry-allwinner-v40-development-board-allwinner-business-units-sdksoftware-management/#comment-543435

**Comment by pfeerick** [comment]
@BPI-SINOVOIP This work has effectively been setting here since March this year (first as a 105 patch, now as a 106) Why no acknowledgement, confirmation that it works, logs of testing on your side or indeed anything? This is not a good sign as to support for this board when it is released, and wouldn't not inspire me to bother purchasing one if this is the reception that community contributions get and what you consider 'open source' to be.

**Comment by dan-and** [comment]
Thank you very much for merging the code. I really appreciate your support.

Kind regards,

Daniel

**Comment by BPI-SINOVOIP** [comment]
Hi Daniel,

Thanks for your patches.

I rolled back the stability issue patch https://github.com/BPI-SINOVOIP/BPI-M2U-bsp/commit/dc7e2042e2712a994f167a702586f76382d74ef8

and we fixed it by commit https://github.com/BPI-SINOVOIP/BPI-M2U-bsp/commit/5525f5cddc66858c271a66410039ab042b22efb3

Please update to latest code and check the stability issue.

thanks

**Comment by dan-and** [comment]
Thanks for the head ups.

**Comment by ThomasKaiser** [comment]
Since a lot of Banana users are for whatever reasons keen on R40/V40 SATA port multiplier support I just gave it a try: https://forum.armbian.com/index.php?/topic/5199-banana-pi-m2u-wont-boot/&do=findComment&comment=39583 (assuming it's as simple as it was with A20 ages ago).

I can neither test (I returned the M2 Berry I had due to false advertising) nor inform Banana users (since those funny guys censor my posts in their forum). Maybe someone else can give it a try? @facat for example?

**Comment by dan-and** [comment]
@ThomasKaiser : I don't have such port multiplier, but I can try to get / lend it from somewhere.

**Comment by ThomasKaiser** [comment]
@dan-and Thanks but I found already someone who tested it. Both 'fix' and 'performance' are the same as with A20 already years ago: https://forum.armbian.com/index.php?/topic/5199-banana-pi-m2u-wont-boot/&do=findComment&comment=39587

Now someone talented and interested would be needed to make this conditional just like Hans did back then and then it would be as easy (and wrong) to use PMs as before with A20 :)

**Pull request merged**
